/*
* generated by Xtext
*/
package example;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return example.ui.internal.LanguageActivator.getInstance().getInjector("example.Language");
	}
	
}
