/**
 * generated by Xtext
 */
package example.validation;

import example.validation.AbstractLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LanguageValidator extends AbstractLanguageValidator {
}
