/*
 * generated by Xtext
 */
package example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LanguageUiModule extends example.ui.AbstractLanguageUiModule {
	public LanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
