/*
 * generated by Xtext
 */
package example;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageRuntimeModule extends example.AbstractLanguageRuntimeModule {

}
