/**
 * generated by Xtext
 */
package example.ui.contentassist;

import example.ui.contentassist.AbstractLanguageProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LanguageProposalProvider extends AbstractLanguageProposalProvider {
}
